[[redirects]]
  from = "https://www.thornsofadragon.com"
  to = "https://thornsofadragon.netlify.app/en/"

[[redirects]]
  from = "https://www.fragmentosdedragon.com/"
  to = "https://thornsofadragon.netlify.app/es/"